version: "2"
services:
  flat-api-db:
    container_name: flat-api-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - flat-api-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - flat-api-db
  flat-api:
    container_name: flat-api
    build:
      context: ./
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - flat-api-db
    volumes:
      - "./:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - flat-api
networks:
  inner: {}
volumes:
  flat-api-db-data: {}
